BEGIN;
DO $$
DECLARE manager_id uuid:=gen_random_uuid(); emp uuid:=gen_random_uuid(); origin uuid:=gen_random_uuid(); origin2 uuid:=gen_random_uuid(); payroll uuid:=gen_random_uuid(); expense uuid:=gen_random_uuid(); returned uuid:=gen_random_uuid(); material_import uuid:=gen_random_uuid(); material_payment uuid:=gen_random_uuid(); staff uuid:=gen_random_uuid(); att uuid; repeated uuid; n numeric;
BEGIN
 INSERT INTO public.users(auth_id,email,full_name,role,is_active) VALUES(manager_id,'advance-test@example.invalid','Advance test','manager',true);
 INSERT INTO public.employees(id,name,daily_salary) VALUES(emp,'Advance test',300000);
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',manager_id,'role','authenticated')::text,true);
 EXECUTE 'SET LOCAL ROLE authenticated';
 INSERT INTO public.advances(id,date,amount,type,purpose,person) VALUES(origin,'2026-10-01',1000,'advance','workshop','Test'),(origin2,'2026-10-01',1000,'advance','workshop','Test');
 INSERT INTO public.expenses(id,date,category,amount) VALUES(expense,'2026-10-01','other',600);
 PERFORM public.reconcile_advance(origin,'expense',expense);
 PERFORM public.reconcile_advance(origin,'expense',expense);
 SELECT outstanding_amount INTO n FROM public.v_advance_balances WHERE id=origin;
 IF n<>400 THEN RAISE EXCEPTION 'Expense counted twice'; END IF;
 BEGIN PERFORM public.reconcile_advance(origin2,'expense',expense); RAISE EXCEPTION 'Duplicate source allowed'; EXCEPTION WHEN check_violation THEN NULL; END;
 BEGIN INSERT INTO public.advances(date,amount,type,original_advance_id,person) VALUES('2026-10-02',500,'settlement',origin,'Test'); RAISE EXCEPTION 'Over-refund allowed'; EXCEPTION WHEN check_violation THEN NULL; END;
 INSERT INTO public.advances(id,date,amount,type,original_advance_id,person) VALUES(returned,'2026-10-02',400,'settlement',origin,'Test');
 SELECT outstanding_amount INTO n FROM public.v_advance_balances WHERE id=origin;
 IF n<>0 THEN RAISE EXCEPTION 'Refund balance mismatch'; END IF;
 BEGIN UPDATE public.advances SET amount=999 WHERE id=origin; RAISE EXCEPTION 'Underfunded source allowed'; EXCEPTION WHEN check_violation THEN NULL; END;
 BEGIN UPDATE public.advances SET purpose='payroll' WHERE id=origin; RAISE EXCEPTION 'Reclassification after posting allowed'; EXCEPTION WHEN check_violation THEN NULL; END;
 INSERT INTO public.advances(id,date,amount,type,purpose,employee_id,person) VALUES(payroll,'2026-10-02',500000,'advance','payroll',emp,'Test');
 att:=public.reconcile_advance(payroll,'payroll_new',NULL);
 repeated:=public.reconcile_advance(payroll,'payroll_new',NULL);
 IF att<>repeated THEN RAISE EXCEPTION 'Payroll retry duplicated'; END IF;
 SELECT net_pay INTO n FROM public.attendance WHERE id=att;
 IF n<>-500000 THEN RAISE EXCEPTION 'Payroll advance must not be clamped'; END IF;
 SELECT outstanding_amount INTO n FROM public.v_advance_balances WHERE id=payroll;
 IF n<>0 THEN RAISE EXCEPTION 'Payroll not reconciled'; END IF;
 BEGIN PERFORM public.reconcile_advance(payroll,'expense',expense); RAISE EXCEPTION 'Wrong purpose allowed'; EXCEPTION WHEN check_violation THEN NULL; END;
 UPDATE public.advances SET purpose='materials' WHERE id=origin2;
 INSERT INTO public.imports(id,date,quantity_kg,price_per_kg) VALUES(material_import,'2026-10-01',200,10);
 INSERT INTO public.payments(id,ref_type,ref_id,amount,date,method) VALUES(material_payment,'import',material_import,1000,'2026-10-01','cash');
 PERFORM public.reconcile_advance(origin2,'payment',material_payment);
 SELECT outstanding_amount INTO n FROM public.v_advance_balances WHERE id=origin2;
 IF n<>0 THEN RAISE EXCEPTION 'Material payment not reconciled'; END IF;
 BEGIN UPDATE public.advances SET amount=1500 WHERE id=origin2; RAISE EXCEPTION 'Posted amount changed'; EXCEPTION WHEN check_violation THEN NULL; END;
 EXECUTE 'RESET ROLE';
 INSERT INTO public.users(auth_id,email,full_name,role,is_active) VALUES(staff,'advance-staff-test@example.invalid','Staff test','staff',true);
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',staff,'role','authenticated')::text,true);
 EXECUTE 'SET LOCAL ROLE authenticated';
 IF EXISTS(SELECT FROM public.v_advance_balances WHERE id=origin) THEN RAISE EXCEPTION 'Staff can see advance balances'; END IF;
 BEGIN PERFORM public.reconcile_advance(origin,'expense',expense); RAISE EXCEPTION 'Staff can reconcile'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 EXECUTE 'RESET ROLE';
END $$;
ROLLBACK;
SELECT 'PASS advance classification and reconciliation' result;
